// Branchesider (SEO-landingssider pr. fag). Indhold pr. fag som ren data — selve
// skabelonen ligger i components/BrancheSide.js. slug = æ/ø-fri URL; fagKey =
// subscriber-fag-nøglen (til /tilmeld?fag=...). nounPlural/nounSingular bruges i
// overskrifter ("for tømrere" / "Start gratis som tømrer"). Alt indhold er
// fag-specifikt; sproget er enkelt og uden absolutte løfter.

// Fælles, platform-handlende sætninger (ens for alle fag — handler om Birdly, ikke faget).
const KORT_SVAR_EXTRA =
  "Opgaverne bliver lagt op på det offentliges egne sider — men der kommer hundredvis hver uge, og de fleste passer ikke til dig. Birdly sorterer i dem og sender dig kun dem, der gør.";
const WHY_HEADING = "Faste opgaver. Sikker betaling.";

export const BRANCHER = [
  {
    slug: "toemrer", fagKey: "tomrer", label: "Tømrer/snedker",
    nounPlural: "tømrere", nounSingular: "tømrer", arbejde: "tømrer- og snedkerarbejde",
    ex1: "et nyt tag på en skole", ex2: "vinduer i en boligforening",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en tømrer kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til tømrere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for tømrere | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for tømrere i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Tagrenovering på skole", desc: "Udskiftning af tag og tagkonstruktion på en folkeskole." },
      { title: "Vinduer i boligforening", desc: "Nye vinduer i en almen boligforening." },
      { title: "Tilbygning til plejehjem", desc: "Tømrerarbejde på udvidelsen af et kommunalt plejehjem." },
      { title: "Nyt halgulv", desc: "Lægning af nyt trægulv i en idrætshal." },
      { title: "Renovering af klasselokaler", desc: "Lofter, gulve og indvendigt træværk på en skole." },
      { title: "Snedkerarbejde i institution", desc: "Døre, inventar og finish i en daginstitution." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange offentlige opgaver er små og passer fint til et lille tømrerfirma — en enkelt skole, en boligforening eller et plejehjem. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en tømreropgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun tømreropgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "murer", fagKey: "murer", label: "Murer",
    nounPlural: "murere", nounSingular: "murer", arbejde: "murer- og betonarbejde",
    ex1: "en facade på et rådhus", ex2: "fliser i en svømmehal",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en murer kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til murere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for murere | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for murere i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Facaderenovering på rådhus", desc: "Murerarbejde på facaden af et rådhus." },
      { title: "Ny skorsten", desc: "Opmuring af ny skorsten på en kommunal bygning." },
      { title: "Omfugning af bygning", desc: "Udskiftning af fuger på en ældre institution." },
      { title: "Flisearbejde i svømmehal", desc: "Nye fliser i en kommunal svømmehal." },
      { title: "Betonreparation", desc: "Reparation af beton på en bro eller bygning." },
      { title: "Murværk på skole", desc: "Reparation af murværk på en folkeskole." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange offentlige opgaver er små og passer fint til et lille murerfirma — en facade, en skorsten eller lidt flisearbejde. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en mur, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun mureropgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "maler", fagKey: "maler", label: "Maler",
    nounPlural: "malere", nounSingular: "maler", arbejde: "malerarbejde",
    ex1: "maling af en hel skole", ex2: "facaden på en institution",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en maler kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til malere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for malere | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for malere i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Maling af skole indvendigt", desc: "Indvendig maling af klasselokaler og gange." },
      { title: "Facademaling på institution", desc: "Maling af facaden på en daginstitution." },
      { title: "Vedligehold af bygninger", desc: "Løbende malerarbejde på kommunens bygninger." },
      { title: "Maling af idrætshal", desc: "Opfriskning af vægge og lofter i en hal." },
      { title: "Træværk og vinduer", desc: "Maling af udvendigt træværk på en ældre bygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange offentlige opgaver er små og passer fint til et lille malerfirma — et par lokaler, en facade eller løbende vedligehold. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en maleropgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun maleropgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "vvs", fagKey: "vvs", label: "VVS & blikkenslager",
    nounPlural: "VVS'ere", nounSingular: "VVS'er", arbejde: "VVS-arbejde",
    ex1: "et nyt varmeanlæg på en skole", ex2: "toiletter i en idrætshal",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en VVS'er kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til VVS'ere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for VVS'ere | Birdly",
    metaDescription: "Få besked når der er en offentlig VVS-opgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Nyt varmeanlæg på skole", desc: "Udskiftning af varmeanlæg på en folkeskole." },
      { title: "Nye toiletter i idrætshal", desc: "Sanitet og VVS i en kommunal idrætshal." },
      { title: "Tagrender på rådhus", desc: "Nye tagrender og inddækning på et rådhus." },
      { title: "Ventilation i institution", desc: "Ventilations- og VVS-arbejde i en daginstitution." },
      { title: "Nye vandrør", desc: "Vandinstallation i et plejehjem under ombygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange offentlige opgaver er små og passer fint til et lille VVS-firma — et varmeanlæg, lidt sanitet eller nye rør. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en VVS-opgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun VVS-opgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "elektriker", fagKey: "elektriker", label: "Elektriker",
    nounPlural: "elektrikere", nounSingular: "elektriker", arbejde: "el-arbejde",
    ex1: "en ny el-tavle i en institution", ex2: "LED-lys i en hal",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en elektriker kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til elektrikere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for elektrikere | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for elektrikere i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Ny el-tavle i institution", desc: "Udskiftning af el-tavle i en daginstitution." },
      { title: "LED-belysning i hal", desc: "Ny LED-belysning i en idrætshal." },
      { title: "El ved renovering af plejehjem", desc: "El-arbejde ved ombygning af et plejehjem." },
      { title: "El til ny tilbygning", desc: "El-installation i en tilbygning til en skole." },
      { title: "Nødbelysning og alarmer", desc: "El-arbejde med nødbelysning i en kommunal bygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange offentlige opgaver er små og passer fint til et lille el-firma — en tavle, ny belysning eller el ved en renovering. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en el-opgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun el-opgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "entreprenor", fagKey: "entreprenor", label: "Entreprenør/anlæg",
    nounPlural: "entreprenører", nounSingular: "entreprenør", arbejde: "anlægs- og jordarbejde",
    ex1: "en ny parkeringsplads", ex2: "byggemodning af et område",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en entreprenør kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til entreprenører. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for entreprenører | Birdly",
    metaDescription: "Få besked når der er en offentlig anlægsopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Anlæg af parkeringsplads", desc: "Ny parkeringsplads ved en kommunal bygning." },
      { title: "Byggemodning", desc: "Byggemodning af et nyt boligområde." },
      { title: "Jordarbejde ved nyt byggeri", desc: "Udgravning og jord ved et nyt byggeri." },
      { title: "Ny vej eller sti", desc: "Anlæg af vej eller cykelsti for kommunen." },
      { title: "Belægning på plads", desc: "Ny belægning på et torv eller en skolegård." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store anlægsopgaver — fra en p-plads til et helt boligområde. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en anlægsopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun anlægsopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "kloak", fagKey: "kloak", label: "Kloak/jord",
    nounPlural: "kloakfirmaer", nounSingular: "kloakfirma", arbejde: "kloak- og jordarbejde",
    ex1: "en kloakrenovering", ex2: "regnvand ved en skole",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et kloakfirma kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til kloakfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for kloakfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig kloak- eller jordopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Kloakrenovering", desc: "Renovering af kloak under en kommunal vej." },
      { title: "Regnvandshåndtering", desc: "Anlæg til at håndtere regnvand ved en skole." },
      { title: "Separatkloakering", desc: "Separatkloakering i et boligområde." },
      { title: "Nye stikledninger", desc: "Nye kloakstik ved en institution." },
      { title: "Jordarbejde til kloak", desc: "Udgravning og jord til et kloakprojekt." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange opgaver er små — et stik, en strækning kloak eller lidt jordarbejde. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en kloak- eller jordopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun kloak- og jordopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "glarmester", fagKey: "glarmester", label: "Glarmester",
    nounPlural: "glarmestre", nounSingular: "glarmester", arbejde: "glas- og vinduesarbejde",
    ex1: "ruder på en skole", ex2: "et glasparti i en indgang",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en glarmester kan én kommunal opgave fylde kalenderen i uger. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til glarmestre. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for glarmestre | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for glarmestre i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Ruder på skole", desc: "Udskiftning af ruder på en folkeskole." },
      { title: "Glasparti i indgang", desc: "Nyt glasparti ved en hovedindgang." },
      { title: "Facadeglas på institution", desc: "Facadeglas på en daginstitution." },
      { title: "Sikkerhedsglas i hal", desc: "Nyt sikkerhedsglas i en idrætshal." },
      { title: "Punkterede termoruder", desc: "Udskiftning af punkterede ruder i en kommunal bygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Mange opgaver er små — et par ruder, et glasparti eller en facade. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en glasopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun glas- og vinduesopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "rengoring", fagKey: "rengoring", label: "Rengøring",
    nounPlural: "rengøringsfirmaer", nounSingular: "rengøringsfirma", arbejde: "rengøring",
    ex1: "fast rengøring af kontorer", ex2: "hovedrengøring af en hal",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et rengøringsfirma kan én kommunal aftale give faste opgaver måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til rengøringsfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for rengøringsfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig rengøringsopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Rengøring af kontorer", desc: "Fast rengøring af kommunale kontorer." },
      { title: "Vinduespudsning på skole", desc: "Vinduespudsning på en folkeskole." },
      { title: "Hovedrengøring af hal", desc: "Hovedrengøring af en idrætshal." },
      { title: "Rengøring af institution", desc: "Daglig rengøring af en daginstitution." },
      { title: "Gulvpleje", desc: "Polering og pleje af gulve i en kommunal bygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra én institution til faste aftaler på flere bygninger. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en rengøringsopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun rengøringsopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "affald", fagKey: "affald", label: "Affald/miljø",
    nounPlural: "affaldsfirmaer", nounSingular: "affaldsfirma", arbejde: "affaldsløsninger",
    ex1: "affaldsindsamling", ex2: "tømning af containere",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et affaldsfirma kan én kommunal aftale give faste opgaver måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til affaldsfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for affaldsfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig affalds- eller miljøopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Affaldsindsamling", desc: "Indsamling af affald for en kommune." },
      { title: "Tømning af containere", desc: "Tømning af containere ved kommunale bygninger." },
      { title: "Miljøsanering", desc: "Sanering af et forurenet område." },
      { title: "Sortering og genbrug", desc: "Håndtering af genbrug på en genbrugsplads." },
      { title: "Byggeaffald", desc: "Bortkørsel af affald fra et byggeprojekt." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra enkelt tømning til faste aftaler. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en affalds- eller miljøopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun affalds- og miljøopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "anlaegsgartner", fagKey: "anlaegsgartner", label: "Anlægsgartner/grønt",
    nounPlural: "anlægsgartnere", nounSingular: "anlægsgartner", arbejde: "pasning af grønne områder",
    ex1: "pasning af grønne områder", ex2: "en ny legeplads",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en anlægsgartner kan én kommunal aftale give faste opgaver sæson efter sæson. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til anlægsgartnere. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for anlægsgartnere | Birdly",
    metaDescription: "Få besked når der er en offentlig grøn opgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Vedligehold af grønne områder", desc: "Pasning af kommunens grønne arealer." },
      { title: "Beplantning ved skole", desc: "Ny beplantning omkring en folkeskole." },
      { title: "Anlæg af legeplads", desc: "Anlæg af en ny legeplads ved en institution." },
      { title: "Pleje af park", desc: "Vedligehold af en kommunal park." },
      { title: "Bede og stier", desc: "Anlæg af bede og stier i et grønt område." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra en legeplads til faste aftaler om pasning. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en grøn opgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun grønne opgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "transport", fagKey: "transport", label: "Transport/vognmand",
    nounPlural: "vognmænd", nounSingular: "vognmand", arbejde: "kørsel og transport",
    ex1: "kørsel af materialer", ex2: "transport for kommunen",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en vognmand kan én kommunal aftale give faste ture måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til vognmænd. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for vognmænd | Birdly",
    metaDescription: "Få besked når der er en offentlig transportopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Kørsel af materialer", desc: "Transport af materialer til et byggeprojekt." },
      { title: "Flytteopgaver", desc: "Flytning for en kommunal arbejdsplads." },
      { title: "Transport for kommunen", desc: "Faste kørselsopgaver for en kommune." },
      { title: "Bortkørsel af jord", desc: "Kørsel af jord fra en byggeplads." },
      { title: "Levering til institutioner", desc: "Levering af varer til kommunale institutioner." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både enkelte ture og faste aftaler — og du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en transportopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun transportopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "arkitekt", fagKey: "arkitekt", label: "Arkitekt",
    nounPlural: "arkitekter", nounSingular: "arkitekt", arbejde: "arkitekt- og tegnearbejde",
    ex1: "tegning af en daginstitution", ex2: "et ombygningsprojekt",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en arkitekt kan én kommunal opgave give måneders arbejde. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til arkitekter. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for arkitekter | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for arkitekter i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Tegning af daginstitution", desc: "Tegninger til en ny daginstitution." },
      { title: "Ombygningsprojekt", desc: "Arkitekt på en ombygning af en skole." },
      { title: "Lokalplan-arbejde", desc: "Hjælp til en lokalplan for kommunen." },
      { title: "Renovering af bygning", desc: "Arkitektarbejde ved renovering af en ældre bygning." },
      { title: "Indretning af kontor", desc: "Indretningsforslag til et kommunalt kontor." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra et enkelt projekt til store opgaver. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en arkitektopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun arkitektopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "ingenior", fagKey: "ingenior", label: "Ingeniør/rådgiver",
    nounPlural: "ingeniører", nounSingular: "ingeniør", arbejde: "rådgivning og beregninger",
    ex1: "rådgivning på et byggeri", ex2: "en energiberegning",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en ingeniør kan én kommunal opgave give måneders arbejde. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til ingeniører. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for ingeniører | Birdly",
    metaDescription: "Få besked når der er en offentlig rådgivningsopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Rådgivning på byggeprojekt", desc: "Teknisk rådgivning på et kommunalt byggeri." },
      { title: "Energiberegning", desc: "Energiberegning på en offentlig bygning." },
      { title: "Statisk beregning", desc: "Statiske beregninger til et byggeprojekt." },
      { title: "Tilstandsrapport", desc: "Gennemgang af en bygnings tilstand." },
      { title: "Projektledelse", desc: "Teknisk projektledelse på en renovering." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra en enkelt beregning til store rådgiveraftaler. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en rådgivningsopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun rådgivningsopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "it", fagKey: "it", label: "IT & software",
    nounPlural: "it-firmaer", nounSingular: "it-firma", arbejde: "it-løsninger og support",
    ex1: "et nyt system til kommunen", ex2: "en support-aftale",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et it-firma kan én kommunal aftale give måneders arbejde. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til it-firmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for it-firmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig it-opgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Nyt system til kommunen", desc: "Et nyt it-system til en kommune." },
      { title: "Support-aftale", desc: "Fast it-support for en offentlig arbejdsplads." },
      { title: "Hjemmeside til institution", desc: "Ny hjemmeside til en institution." },
      { title: "Drift og hosting", desc: "Drift af systemer for en kommune." },
      { title: "Digital løsning", desc: "Udvikling af en digital løsning til borgerne." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra en hjemmeside til store systemer. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en it-opgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun it-opgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "service", fagKey: "service", label: "Service & vedligehold",
    nounPlural: "servicefirmaer", nounSingular: "servicefirma", arbejde: "service og vedligehold",
    ex1: "en serviceaftale på bygninger", ex2: "teknisk vedligehold",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et servicefirma kan én kommunal aftale give faste opgaver måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til servicefirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for servicefirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig service- eller vedligeholdsopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Serviceaftale på bygninger", desc: "Fast serviceaftale på kommunale bygninger." },
      { title: "Teknisk vedligehold", desc: "Vedligehold af tekniske installationer." },
      { title: "Facility-opgaver", desc: "Facility-service på en offentlig arbejdsplads." },
      { title: "Eftersyn og småreparationer", desc: "Løbende eftersyn af en kommunal bygning." },
      { title: "Vedligehold af anlæg", desc: "Service på tekniske anlæg i en hal." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra et enkelt eftersyn til faste serviceaftaler. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en serviceopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun service- og vedligeholdsopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "forretningsservice", fagKey: "forretningsservice", label: "Revisor/advokat/forretningsservice",
    nounPlural: "revisorer og advokater", nounSingular: "rådgiver", arbejde: "revision og rådgivning",
    ex1: "revision for en kommunal enhed", ex2: "juridisk rådgivning",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For en rådgiver kan én offentlig aftale give måneders arbejde. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til revisorer og advokater. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for revisorer og advokater | Birdly",
    metaDescription: "Få besked når der er en offentlig opgave for revisorer og advokater i dit område. Birdly sender en SMS — gratis i 14 dage.",
    examples: [
      { title: "Revision for kommunal enhed", desc: "Revision af regnskab for en kommunal enhed." },
      { title: "Juridisk rådgivning", desc: "Juridisk rådgivning til en offentlig arbejdsplads." },
      { title: "Konsulentopgave", desc: "Konsulentopgave for en kommune." },
      { title: "Regnskab og bogføring", desc: "Bogføring for en offentlig enhed." },
      { title: "Analyse og rapport", desc: "Udarbejdelse af en analyse for kommunen." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra en enkelt rådgivningsopgave til faste aftaler. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en opgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun opgaver inden for mit felt?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "catering", fagKey: "catering", label: "Mad & catering",
    nounPlural: "cateringfirmaer", nounSingular: "cateringfirma", arbejde: "mad og catering",
    ex1: "kantinedrift", ex2: "mad til et plejehjem",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et cateringfirma kan én kommunal aftale give faste leveringer måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til cateringfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for cateringfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig mad- eller cateringopgave i dit område. Birdly sender dig en SMS — gratis i 14 dage.",
    examples: [
      { title: "Kantinedrift", desc: "Drift af en kantine på en arbejdsplads." },
      { title: "Mad til plejehjem", desc: "Levering af mad til et plejehjem." },
      { title: "Catering til arrangementer", desc: "Catering til kommunale arrangementer." },
      { title: "Mad til institution", desc: "Mad til en daginstitution." },
      { title: "Mødeforplejning", desc: "Forplejning til møder og kurser." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra et enkelt arrangement til faste leveringer. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en mad- eller cateringopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun mad- og cateringopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "inventar", fagKey: "mobler", label: "Møbler & inventar",
    nounPlural: "møbelfirmaer", nounSingular: "møbelfirma", arbejde: "møbler og inventar",
    ex1: "møbler til en skole", ex2: "inventar til et kontor",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et møbelfirma kan én kommunal ordre fylde ordrebogen. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til møbelfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for møbelfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig møbel- eller inventaropgave i dit område. Birdly sender en SMS — gratis i 14 dage.",
    examples: [
      { title: "Møbler til skole", desc: "Nye møbler til en folkeskole." },
      { title: "Inventar til kontor", desc: "Inventar til et kommunalt kontor." },
      { title: "Indretning af institution", desc: "Møbler og indretning af en daginstitution." },
      { title: "Møbler til plejehjem", desc: "Nye møbler til et plejehjem." },
      { title: "Reoler og opbevaring", desc: "Reoler og opbevaring til en offentlig bygning." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store ordrer — fra et enkelt lokale til en hel institution. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en møbel- eller inventaropgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun møbel- og inventaropgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },

  {
    slug: "vagt", fagKey: "vagt", label: "Vagt & sikring",
    nounPlural: "vagtfirmaer", nounSingular: "vagtfirma", arbejde: "vagt og sikring",
    ex1: "en vagtordning", ex2: "et alarmsystem",
    kortSvarExtra: KORT_SVAR_EXTRA, whyHeading: WHY_HEADING,
    whyText: "Det offentlige er en af de største kunder i Danmark — og de betaler altid til tiden. For et vagtfirma kan én kommunal aftale give faste opgaver måned efter måned. Mange firmaer byder aldrig, fordi de tror det er svært, eller de opdager opgaverne for sent. Det er præcis dér, Birdly hjælper: du får besked, mens der stadig er tid til at byde.",
    eksemplerIntro: "Her er nogle af de opgaver, vi har sendt til vagtfirmaer. Hvad du selv får, afhænger af det, du vælger ved oprettelsen — om du vil have et bredt udvalg eller kun de helt rigtige, hvilket område du dækker, og hvor store opgaver du er ude efter. Du bestemmer, vi holder øje.",
    title: "Offentlige opgaver for vagtfirmaer | Birdly",
    metaDescription: "Få besked når der er en offentlig vagt- eller sikringsopgave i dit område. Birdly sender en SMS — gratis i 14 dage.",
    examples: [
      { title: "Vagtordning", desc: "Vagtordning på kommunale bygninger." },
      { title: "Alarmsystem", desc: "Nyt alarmsystem i en offentlig bygning." },
      { title: "Adgangskontrol", desc: "Adgangskontrol på en arbejdsplads." },
      { title: "Rundering", desc: "Fast rundering ved kommunale bygninger." },
      { title: "Overvågning", desc: "Overvågningsløsning til en institution." },
    ],
    faq: [
      { q: "Skal jeg være et stort firma for at byde?", a: "Nej. Der er både små og store opgaver — fra et alarmsystem til faste vagtaftaler. Du byder kun på det, du kan løfte." },
      { q: "Hvad koster det at byde på en opgave?", a: "Selve det at byde koster ikke noget. Du bruger din tid på at lægge et tilbud — og Birdly sørger for, at du overhovedet ser opgaven i tide." },
      { q: "Hvordan finder jeg opgaverne?", a: "Det gør Birdly for dig. Du fortæller os dit fag og dit område, og vi sender dig en SMS, når der er en vagt- eller sikringsopgave, der matcher dine valg. Ingen portal, ingen søgning." },
      { q: "Får jeg kun vagt- og sikringsopgaver?", a: "Vi sender kun besked, når en opgave matcher det, du har valgt. Vil du have flere eller færre beskeder, kan du altid ændre dine valg." },
    ],
  },
];

const BY_SLUG = Object.fromEntries(BRANCHER.map((b) => [b.slug, b]));
export function getBranche(slug) {
  return BY_SLUG[slug] || null;
}
